In [1]:
# Dependencies
import pandas as pd
import matplotlib.pyplot as plt
from sqlalchemy import create_engine
from sqlalchemy import Table, Column, Integer, String, MetaData, Float

In [2]:
dfs = []
for year in range(2016, 2019):
    print(f'Loading {year}...')
    df = pd.read_excel(f'/Users/hardings/Desktop/bootcamp/project_2/Medicare_Provider_Charge_Inpatient_DRGALL_FY{year}.xlsx', header=5)
    df['Year'] = year
    dfs.append(df)
medicare_data = pd.concat(dfs, axis=0)

Loading 2016...
Loading 2017...
Loading 2018...

In [3]:
medicare_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 586611 entries, 0 to 193002
Data columns (total 13 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   DRG Definition                              586611 non-null  object
 1   Provider Id                                 586611 non-null  int64
 2   Provider Name                               586611 non-null  object
 3   Provider Street Address                     586611 non-null  object
 4   Provider City                               586611 non-null  object
 5   Provider State                              586611 non-null  object
 6   Provider Zip Code                           586611 non-null  int64
 7   Hospital Referral Region (HRR) Description  586611 non-null  object
 8   Total Discharges                            586611 non-null  int64
 9   Average Covered Charges                     586611 non-null  float64
 10  Average Total Payments                      586611 non-null  float64
 11  Average Medicare Payments                   586611 non-null  float64
 12  Year                                        586611 non-null  int64
dtypes: float64(3), int64(4), object(6)
memory usage: 62.7+ MB

In [4]:
medicare_data.columns = medicare_data.columns.str.replace(' ','_')
medicare_data = medicare_data.rename({'Hospital_Referral_Region_(HRR)_Description':'HRR'}, axis = 1)

In [5]:
medicare_data.head()

,DRG_Definition,Provider_Id,Provider_Name,Provider_Street_Address,Provider_City,Provider_State,Provider_Zip_Code,HRR,Total_Discharges,Average_Covered_Charges,Average_Total_Payments,Average_Medicare_Payments,Year
0,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,10033,UNIVERSITY OF ALABAMA HOSPITAL,619 SOUTH 19TH STREET,BIRMINGHAM,AL,35233,AL - Birmingham,13,1.016806e+06,296937.000000,150139.692308,2016
1,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,30103,MAYO CLINIC HOSPITAL,5777 EAST MAYO BOULEVARD,PHOENIX,AZ,85054,AZ - Phoenix,26,4.433875e+05,215059.538462,163889.307692,2016
2,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,40114,BAPTIST HEALTH MEDICAL CENTER-LITTLE ROCK,"9601 INTERSTATE 630, EXIT 7",LITTLE ROCK,AR,72205,AR - Little Rock,33,7.114720e+05,180315.545455,145192.606061,2016
3,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,50025,UC SAN DIEGO HEALTH HILLCREST - HILLCREST MED CTR,200 WEST ARBOR DRIVE,SAN DIEGO,CA,92103,CA - San Diego,17,7.963438e+05,299244.411765,270131.588235,2016
4,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,50100,SHARP MEMORIAL HOSPITAL,7901 FROST ST,SAN DIEGO,CA,92123,CA - San Diego,13,1.434651e+06,239537.461538,215205.000000,2016

In [6]:
# Create database connection
connection_string = "postgres:postgres@localhost:5432/medicare_drg"
engine = create_engine(f'postgresql://{connection_string}')

In [7]:
# create table for this data
meta = MetaData()

inpatient = Table(
   'inpatient', meta, 
    Column('DRG_Definition', String),
    Column('Provider_Id', Integer),
    Column('Provider_Name', String),
    Column('Provider_Street_Address', String), 
    Column('Provider_City', String), 
    Column('Provider_State', String), 
    Column('Provider_Zip_Code', Integer), 
    Column('HRR', String), 
    Column('Total_Discharges', Integer),
    Column('Average_Covered_Charges', Float),
    Column('Average_Total_Payments', Float),
    Column('Average_Medicare_Payments', Float),
    Column('Year', Integer)
)

meta.create_all(engine)

In [8]:
# Check table names
engine.table_names()

['inpatient']

In [11]:
# Load dataframes into database
medicare_data.to_sql(name='inpatient', con=engine, if_exists='append', index=False)

In [12]:
# Check to see if data loaded in
pd.read_sql_query('select * from inpatient limit 100', con=engine).head()

,DRG_Definition,Provider_Id,Provider_Name,Provider_Street_Address,Provider_City,Provider_State,Provider_Zip_Code,HRR,Total_Discharges,Average_Covered_Charges,Average_Total_Payments,Average_Medicare_Payments,Year
0,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,10033,UNIVERSITY OF ALABAMA HOSPITAL,619 SOUTH 19TH STREET,BIRMINGHAM,AL,35233,AL - Birmingham,13,1.016806e+06,296937.000000,150139.692308,2016
1,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,30103,MAYO CLINIC HOSPITAL,5777 EAST MAYO BOULEVARD,PHOENIX,AZ,85054,AZ - Phoenix,26,4.433875e+05,215059.538462,163889.307692,2016
2,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,40114,BAPTIST HEALTH MEDICAL CENTER-LITTLE ROCK,"9601 INTERSTATE 630, EXIT 7",LITTLE ROCK,AR,72205,AR - Little Rock,33,7.114720e+05,180315.545455,145192.606061,2016
3,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,50025,UC SAN DIEGO HEALTH HILLCREST - HILLCREST MED CTR,200 WEST ARBOR DRIVE,SAN DIEGO,CA,92103,CA - San Diego,17,7.963438e+05,299244.411765,270131.588235,2016
4,001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...,50100,SHARP MEMORIAL HOSPITAL,7901 FROST ST,SAN DIEGO,CA,92123,CA - San Diego,13,1.434651e+06,239537.461538,215205.000000,2016